name: Calculate and Upload KPIs

# on:
#   schedule:
#     - cron: '*/10 * * * *' # Runs every 10 minutes
#   pull_request:
#     branches:
#       - kathy/scripts-reuse

jobs:
  calculate-and-upload-KPIs:
    name: Calculate and Upload KPIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
        with:
          project_id: divvi-staging
          credentials_json: ${{ secrets.DIVVI_STAGING_UPLOADER_SERVICE_ACCOUNT_KEY }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: 'package.json'
          check-latest: true
      - run: yarn
      - name: Calculate and upload KPIs
        run: yarn ts-node scripts/calcAndUploadKPIs.ts

      # TODO(kathy)
      # - name: Notify Slack on Failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     channel-id: 'alerts'
      #     slack-message: '❌ KPI calculation and upload workflow failed! Check the run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
